action_max: [549.942626953125, 162.24717712402344, 943.5411987304688, 1.0]
action_min: [394.0250244140625, -271.37451171875, 718.0595703125, 0.0]
action_scale: [77.95880126953125, 216.81085205078125, 112.74081420898438, 0.5]
action_bias: [471.98382568359375, -54.56366729736328, 830.8004150390625, 0.5]
robot_ee_pos:
  obs_max: [539.505859375, 157.7537841796875, 938.3877563476562, 1.0]
  obs_min: [399.60650634765625, -278.2024230957031, 722.0260620117188, 0.0]
  obs_scale: [69.94967651367188, 217.9781036376953, 108.18084716796875, 0.5]
  obs_bias: [469.5561828613281, -60.22431945800781, 830.2069091796875, 0.5]
