init_pose:
 - 299.072
 - 55.935
 - 51.4356
 - 58.4128
 - -60.4091
 - -54.6146
 - -29.7137
 - 470.842
 - -46.1685
 - -4.37678
 - -96.5784
 - -103.459
 - -87.2614
 - -82.6026
 - 416.874
 - 0.0
 - 74.2702
